# Generated by Django 2.2.6 on 2019-12-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191125_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookPdf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='BPdf',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='books'),
        ),
    ]
