# Generated by Django 2.2.6 on 2019-12-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='author_image'),
        ),
    ]
