# Generated by Django 2.2.6 on 2019-12-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_language_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='image',
        ),
    ]
